### PR TITLE
Add GPU tests

### PR DESCRIPTION
**Pull request by samhatfield**
This PR tidies up the testing structure and adds tests for the GPU version.

I had to undo PR #158 as it causes a crash on our system: `invalid device buffer`.

I also had to disable the `--nfld 0` test as this fails on GPU.

This PR builds on #175.

### CODE REVIEW

**Review by reuterbal — COMMENTED** [review]
Looks great, many thanks!

**Comment by samhatfield** [comment]
I'm not able to reproduce the two tests failing ac-gpu manually.

**Comment by reuterbal** [comment]
I think I might know where the test failures come from: We're building with GPU-aware MPI but are running with the default hpcx-openmpi module that doesn't have GPU-aware MPI baked in. I suppose we may have to specify module versions after all.

In addition, you can also try changing the `sbatch` headers to `--mem=0`. That might have been what broke the pinning maybe, if it can't get enough pages.

**Comment by samhatfield** [comment]
> I think I might know where the test failures come from: We're building with GPU-aware MPI but are running with the default hpcx-openmpi module that doesn't have GPU-aware MPI baked in. I suppose we may have to specify module versions after all.

That's certainly possible, but other tests with `NPROC > 1` succeeded, e.g. `ectrans-benchmark-gpu-sp_T47_O48_mpi2_omp1_nfld10_nlev20_nproma16`. Only the following two are failing:
```
ectrans-benchmark-gpu-dp_T47_O48_mpi2_omp1_nfld10
ectrans-benchmark-gpu-sp_T47_O48_mpi2_omp1_nfld10
```

> In addition, you can also try changing the `sbatch` headers to `--mem=0`. That might have been what broke the pinning maybe, if it can't get enough pages.

I'll give that a go!

**Comment by samhatfield** [comment]
Given that the last commit (9699c64) gives the same error, I think the issue is with linking with `-cuda` rather than using pinned memory.

**Comment by samhatfield** [comment]
Good to go I think. @wdeconinck any strong feelings regarding the CMake changes?

**Pull request merged**
