### PR TITLE
Fix bug in PSPSC3A inverse Legendre transform packing

### PR DESCRIPTION
**Pull request by samhatfield**
Previously each field of PSPSC3A after the first was overwriting the previous one, and the packing index (IFIRST) wasn't advancing as each field was packed.

### CODE REVIEW

**Comment by wdeconinck** [comment]
Nice catch, is this not a commonly used option?

**Comment by samhatfield** [comment]
All credit to Nils! No I guess we don't usually call with multiple 3D scalar fields.

**Comment by wdeconinck** [comment]
@samhatfield Can you also apply this change to the "develop" branch's CPU code? This will then make its way to the cpu version here automatically as well when merged.

**Comment by samhatfield** [comment]
I don't think this bug affects the CPU version? https://github.com/ecmwf-ifs/ectrans/blob/develop/src/trans/internal/ltinv_mod.F90#L180

**Comment by wdeconinck** [comment]
Do we have a test to catch this bug?

**Review by wdeconinck — APPROVED** [review]

**Pull request merged**
