### PR TITLE
Some changes related to CONTIGUOUS

### PR DESCRIPTION
**Pull request by DJDavies2**
This is for #93, it seems to fix the Intel issue.

I don't know if this is acceptable as it removes the CONTIGUOUS from a dummy argument.  I think this is a problem with the compiler.

### CODE REVIEW

**Comment by samhatfield** [comment]
Could you send this PR to ecmwf-ifs:develop instead of ecmwf-ifs:main?

**Comment by DJDavies2** [comment]
> Could you send this PR to ecmwf-ifs:develop instead of ecmwf-ifs:main?

I see this has been done?

**Comment by DJDavies2** [comment]
Will it be possible to get this change merged?

**Comment by samhatfield** [comment]
I have no problem with it personally, but we need to check this is okay with our Météo-France colleagues as they introduced the `CONTIGUOUS` statements. I'll try to get an answer from them.

**Comment by DJDavies2** [comment]
Closing as #93 is closed.

**Pull request closed without merging**
