### PR TITLE
Fix undefined variable and clean up LEDIR

### PR DESCRIPTION
**Pull request by lukasm91**
- *Critical*: `ISKIP` was undefined in the last loop
- Completely got rid of ISKIP and replace with a simple condition
- Change the parallelization scheme for simplicity of the code

Note: I applied the 3rd point more widely, but this is yet to come after I checked performance behavior. 
- The change in this PR does not cause significant runtime changes.
- The change in this PR *change* results!

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](http://claassistant.ecmwf.int:80/ecmwf-ifs/ectrans?pullRequest=1) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](http://claassistant.ecmwf.int:80/ecmwf-ifs/ectrans?pullRequest=1) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:80/check/ecmwf-ifs/ectrans?pullRequest=1) it.</sub>

**Comment by samhatfield** [comment]
I guess the changes in this PR are already present in @marsdeno's redgreen-optimized. Need to check.

**Comment by samhatfield** [comment]
I guess I can close this now @lukasm91?

**Comment by lukasm91** [comment]
this is  ancient, so yes, of course :+1:

**Pull request closed without merging**
