### PR TITLE
Add a pragma guard around OpenMP directives to fix a bug with GNU10.1/10.2

### PR DESCRIPTION
**Pull request by shlyaeva**
Adds pragmas to turn off an OpenMP-parallelization of one loop that segfaults with GNU10.1/10.2 (and possibly 10.0), see details and discussion in https://github.com/ecmwf-ifs/ectrans/issues/20.

Fixes https://github.com/ecmwf-ifs/ectrans/issues/20

### CODE REVIEW

**Comment by wdeconinck** [comment]
Thanks @shlyaeva all good. Just waiting for your CLA signature.

**Comment by shlyaeva** [comment]
Thank you @wdeconinck! I signed the agreement, maybe it takes some time to show up?

**Comment by wdeconinck** [comment]
> Thank you @wdeconinck! I signed the agreement, maybe it takes some time to show up?

I think it's possible your user email used to make the commit is not registered in your GitHub profile. When hovering over the "committer" it doesn't allow me to click as it does with other commits.

**Review by climbfuji — APPROVED** [review]

**Comment by shlyaeva** [comment]
@wdeconinck I corrected the email to the one associated with my profile, and force-pushed that change here, should be all good now.

**Pull request merged**
