### PR TITLE
Enable GPU feature without MPI requirement

### PR DESCRIPTION
**Pull request by wdeconinck**
This solves #138 by introducing preprocessor guards around MPI includes and symbols

### CODE REVIEW

**Review by marsdeno — APPROVED** [review]
Looks ok to me.
Indentation of the fortran is getting harder to follow in some places with the number of preprocessor guards we're using, but that is not the fault of this PR!

**Comment by wdeconinck** [comment]
Once MPI is replaced by MPL we should have access to all symbols again, and the preprocessor guards can be removed.

**Comment by samhatfield** [comment]
Looks good. However note that although you can now build ecTrans/GPU without MPI, you still can't run it. So MPI is still effectively required for running on GPUs, even with a single MPI task. Since this is (hopefully) temporary, this is nitpicking.

**Comment by wdeconinck** [comment]
> Looks good. However note that although you can now build ecTrans/GPU without MPI, you still can't run it. So MPI is still effectively required for running on GPUs, even with a single MPI task. Since this is (hopefully) temporary, this is nitpicking.

You will be happy to learn I was successful at running GPU code without linking to any MPI library this way. This is because the calls to MPI are guarded at runtime with `IF`s that relate to send/receive counts that amount to zero.

**Comment by samhatfield** [comment]
That's great! I assumed that TRLTOG/GTOL were not clever enough to handle NPROC=1 without issuing MPI calls, unlike TRLTOM/MTOL which has a separate code path. But clearly I'm wrong.

**Review by samhatfield — APPROVED** [review]

**Pull request merged**
