### PR TITLE
Remove NCOMBFLEN parameter

### PR DESCRIPTION
**Pull request by samhatfield**
This wasn't used anywhere.

### CODE REVIEW

**Comment by wdeconinck** [comment]
Interesting find. I wonder when it was removed...

Similar to a previous cleanup, I would ask to keep the API stable but deprecate the use of kcombflen in setup_trans0 because this parameter is still used in e.g. [ifs-source/arpifs/setup/sutrans0.F90](https://git.ecmwf.int/projects/IFS/repos/ifs-source/browse/arpifs/setup/sutrans0.F90?at=refs%2Fheads%2Fmaster)

Definitely however we should have another ifs-source commit to fix the use of these deprecated parameters.

**Review by wdeconinck — CHANGES_REQUESTED** [review]
Please keep external API stable with deprecation warning for the time being

**Comment by samhatfield** [comment]
It was removed [16 years ago](https://github.com/ecmwf-ifs/ectrans/commit/8aaf3ec28d4b41a22135a8acd98b4901cbe5421f#diff-cec309202e471a4e0fe8adc60e8c9dcecd4034195e8e3fba9e728e67b8be7183L102) :p

But yes I will keep the argument but issue a warning. Just a second.

**Comment by samhatfield** [comment]
PR updated.

**Comment by wdeconinck** [comment]
16!!! years? Good riddance.

**Review by wdeconinck — APPROVED** [review]

**Pull request merged**
