### PR TITLE
Feature/dirtransadj

### PR DESCRIPTION
**Pull request by MarekWlasak**
This PR extends the transi interface to use the adjoint of the direct spectral transform.

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](http://claassistant.ecmwf.int:80/ecmwf-ifs/ectrans?pullRequest=10) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](http://claassistant.ecmwf.int:80/ecmwf-ifs/ectrans?pullRequest=10) before we can accept your contribution.<br/>**0** out of **4** committers have signed the CLA.<br/><br/>:x: samhatfield<br/>:x: wdeconinck<br/>:x: marsdeno<br/>:x: MarekWlasak<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:80/check/ecmwf-ifs/ectrans?pullRequest=10) it.</sub>

**Comment by MarekWlasak** [comment]
Hi @wdeconinck  @samhatfield - for some reason I have not been able to branch off the ecmwf-ifs develop, but instead branch off "main".  I don't seem to be able to access ecmwf-ifs develop in my fork.  Is that intentional?

**Comment by samhatfield** [comment]
Hi @MarekWlasak - I'm not actually sure what the purpose of develop is with ecTrans, since it's ~40 commits out-of-date. @wdeconinck will know?

**Comment by wdeconinck** [comment]
Thanks @MarekWlasak  That looks great!
The develop branch should be leading main indeed. Something is not right :)

**Pull request merged**
