### PR TITLE
asre1b_mod fix

### PR DESCRIPTION
**Pull request by PaulMullowney**
Missing collapse statement in the omp code improves performance in th…e ectrans benchmark

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf-ifs/ectrans?pullRequest=35) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf-ifs/ectrans?pullRequest=35) before we can accept your contribution.<br/><hr/>**Paul Mullowney** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf-ifs/ectrans?pullRequest=35) it.</sub>

**Comment by PaulMullowney** [comment]
I don't understand what else I need to do with the contributor license agreement. I've tried to sign it.

**Comment by wdeconinck** [comment]
> I don't understand what else I need to do with the contributor license agreement. I've tried to sign it.

Could it be that the email address of the particular commit is not registered in GitHub? That could explain it.

**Comment by PaulMullowney** [comment]
> > I don't understand what else I need to do with the contributor license agreement. I've tried to sign it.
> 
> Could it be that the email address of the particular commit is not registered in GitHub? That could explain it.

Your comment on this thread came to my AMD email address.

**Comment by wdeconinck** [comment]
I see in the commit:
```
commit cee87b854d5ae527fdc6c5cb246e9082a6478140 (origin/asre1b_mod_fix)
Author: Paul Mullowney <Paul.Mullowney@nrel.gov>
Date:   Mon Aug 28 18:36:54 2023 -0400
```
This email address listed above is not registered in your GitHub account, so GitHub does not know this is you. Also when I hover over the committer of that commit, it is not a clickable link, which it normally should be.
You can have multiple email addresses linked to your GitHub account, that is not a problem.

**Comment by PaulMullowney** [comment]
> I see in the commit:
> 
> ```
> commit cee87b854d5ae527fdc6c5cb246e9082a6478140 (origin/asre1b_mod_fix)
> Author: Paul Mullowney <Paul.Mullowney@nrel.gov>
> Date:   Mon Aug 28 18:36:54 2023 -0400
> ```
> 
> This email address listed above is not registered in your GitHub account, so GitHub does not know this is you. Also when I hover over the committer of that commit, it is not a clickable link, which it normally should be. You can have multiple email addresses linked to your GitHub account, that is not a problem.

I think I have it fixed now.

**Comment by wdeconinck** [comment]
Thanks @PaulMullowney for this contribution!

**Pull request merged**
